# Generated by Django 5.1.1 on 2024-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("activate", "Activate"),
                    ("blocked", "Blocked"),
                    ("deleted", "Deleted"),
                    ("completed", "Completed"),
                ],
                default="activate",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
