# Generated by Django 5.1.1 on 2024-09-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_description_product_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Address",
            new_name="Description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Fees",
            new_name="Price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("canceld", "Canceled"),
                    ("progress", "Progress"),
                    ("deleted", "Deleted"),
                    ("delivered", "Delivered"),
                ],
                default="activate",
                max_length=20,
            ),
        ),
    ]
